# 行列積のスクラッチ

In [2]:
import numpy as np

# 【問題１】行列積を手計算する

In [3]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print('A\n',a_ndarray,'\n\nB\n',b_ndarray)

A
 [[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]] 

B
 [[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


* m×n行列とn×k行列の積はm×k行列になる
* 行列AとBの積は３×３行列になり，仮に行列Cとする
* 行列Aは行方向に，行列Bは列方向に見る
* 行列Cの(1,1)成分は，行列Aの１行目の各要素と行列Bの１列目の各要素の積の総和
* 行列C(1,1)要素 = (-1×0) + (2×0) + (3×2) = 6
* 行列C(1,2)要素 = (-1×2) + (2×2) + (3×9) = 29
* 行列C(1,3)要素 = (-1×1) + (2×-8) + (3×-1) = -20
* 行列C(2,1)要素 = (4×0) + (-5×0) + (6×2) = 12
* 行列C(2,2)要素 = (4×2) + (-5×2) + (6×9) = 52
* 行列C(2,3)要素 = (4×1) + (-5×-8) + (6×-1) = 38
* 行列C(3,1)要素 = (7×0) + (8×0) + (-9×2) = -18
* 行列C(3,2)要素 = (7×2) + (8×2) + (-9×9) = -51
* 行列C(3,3)要素 = (7×1) + (8×-8) + (-9×-1) = -48

* **メモ：jupyterの検索置換はコマンドモードでF**

# 【問題２】numpy関数による計算

In [4]:
# np.matmul()
np.matmul(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [5]:
# np.dot()
np.dot(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [6]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【問題３】ある要素の計算実装

In [7]:
# 計算結果を入れるndarray
c_ndarray = np.zeros((a_ndarray.shape[0],b_ndarray.shape[1]),dtype=a_ndarray.dtype)

for i in range(a_ndarray.shape[0]):
    for j in range(b_ndarray.shape[1]):
        for k in range(a_ndarray.shape[1]):
            c_ndarray[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題４】行列積を行う関数の作成

In [11]:
def matrix_dot(A,B):
    """
    行列積を行う関数
    
    Parameters
        ----------
    A : ndarray, shape (m,k)
    B : ndarray, shape (k,n)
    
    Returns
    -------
    C : ndarray ,shape(m,n)
    """
    
    C = np.zeros((A.shape[0],B.shape[1]),dtype=A.dtype)
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                C[i, j] += A[i, k] * B[k, j]
    return C

In [12]:
matrix_dot(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【問題５】計算が定義されない入力を判定する

In [16]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print('d_ndarray_shape:',d_ndarray.shape)
print('e_ndarray_shape:',e_ndarray.shape)

d_ndarray_shape: (2, 3)
e_ndarray_shape: (2, 3)


In [29]:
def matrix_dot_error(A,B):
    """
    行列積を行う関数
    
    Parameters
        ----------
    A : ndarray
    B : ndarray
    
    Returns
    -------
    C : ndarray 
    """
    A_shape = A.shape[1]
    B_shape = B.shape[0]
    if A_shape != B_shape:
        print ('左の行列の列数と右の行列の行数が等しくない')
    else:
        C = np.zeros((A.shape[0],B.shape[1]),dtype=A.dtype)
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                for k in range(A.shape[1]):
                    C[i, j] += A[i, k] * B[k, j]
        return C

In [30]:
matrix_dot_error(d_ndarray,e_ndarray)

左の行列の列数と右の行列の行数が等しくない


# 【問題６】転置

In [34]:
# .T
matrix_dot_error(d_ndarray,e_ndarray.T)

array([[ 46,  -4],
       [-34,  73]])

In [35]:
# np.transpose
matrix_dot_error(d_ndarray,np.transpose(e_ndarray))

array([[ 46,  -4],
       [-34,  73]])